'use client'

import Image from 'next/image'
import { useState } from 'react'
import { ArrowRight, Check, ChevronDown, Menu, X } from 'lucide-react'
import { ContactForm } from '@/components/contact-form'
import { RoiCalculator } from '@/components/roi-calculator'

const logoUrl = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-HpVwXi91yoonvKMYsveI3dcnZJdWfl.png'
const mapGreenUrl = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-Wiy4oFynSb4D83BYxxd5Tkm85UqSKs.png'
const mapRedUrl = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-qJiF3P7KItL1ue8why3gI2uBrtwQDU.png'
const founderUrl = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-y88XjYdJnxwVQIKpJuP6T5fGVjwBKj.png'

const webFeatures = [
  ['Egyedi dizájn', 'Az Ön vállalkozásához és célközönségéhez igazított megjelenés, nem sablon, hanem személyre szabott arculat.'],
  ['Mobilbarát kialakítás', 'Minden eszközön jól működő, gyorsan betöltődő oldal, amely telefonról is kényelmesen használható.'],
  ['Kapcsolatfelvételi űrlap', 'Egyszerű, megbízható űrlap, amelyen keresztül az érdeklődők könnyen üzenetet küldhetnek.'],
  ['Foglalási rendszerek', 'Időpontfoglalás és ajánlatkérés, ha a vállalkozásának erre van szüksége.'],
  ['SEO alapok', 'Technikai és tartalmi alapok a jobb online megtalálhatóságért.'],
  ['Gyors betöltés', 'Optimalizált oldal, amely nem veszíti el a látogatókat.'],
]

const industries = ['Villanyszerelők', 'Klímaszerelők', 'Burkolók', 'Autószervizek', 'Vízvezeték-szerelők', 'Tetőfedők / tetőjavítás', 'Ácsok', 'Bádogosok', 'Duguláselhárítók', 'Favágók', 'Fürdőszoba-felújítók', 'Gipszkartonosok', 'Kerítésépítők', 'Kertépítők', 'Kőművesek', 'Lakásfelújítók', 'Napelem-telepítők', 'Nyílászáró-beépítők', 'Térkövezők', 'Zárszervizek']

const roadmap = [
  ['ALAPOK', '1–14. nap', [['1. nap', 'Audit. Átvizsgáljuk a Google Cégprofilját, és pontosan megmutatjuk, mi nincs rendben vele.'], ['3. nap', 'A kategóriákat, szolgáltatásokat és szolgáltatási területet azokhoz a keresésekhez igazítjuk, amelyeket az ügyfelek valóban használnak.'], ['7. nap', 'A szükséges profilbeállításokat és területi struktúrát rendbe tesszük.'], ['14. nap', 'A szükséges weboldal-oldalak elkészülnek vagy optimalizálva lesznek, és összekapcsoljuk őket a Google Cégprofillal.']]],
  ['TEKINTÉLY', '15–45. nap', [['21. nap', 'Elindulnak a rendszeres Google Cégprofil-frissítések a fontos szolgáltatási területekre és munkákra építve.'], ['30. nap', 'Elindítjuk az értékelésgyűjtési folyamatot, hogy az elégedett ügyfelek tapasztalatai is erősítsék a vállalkozás hitelességét.'], ['45. nap', 'Átnézzük a térképes versenytársakat, és ha egyértelműen szabálytalan vagy megtévesztő profilokat találunk, a Google hivatalos rendszerén keresztül jelezzük őket.']]],
  ['TOP 3', '46–90. nap', [['60. nap', 'A cél, hogy egyre több fontos keresésnél megjelenjen a vállalkozás a Google Térkép első találatai között.'], ['75. nap', 'Erősítjük és követjük a helyezéseket a megállapodott szolgáltatási terület fontos pontjain és keresésein.'], ['90. nap', 'Top 3 — vagy díjmentesen dolgozunk tovább, amíg el nem érjük.']]],
] as const

const faqs = [
  ['Mit jelent pontosan a Google Térkép Top 3?', 'Top 3 helyezést a Google Térkép találatai között azokra a keresésekre, amelyeket az ügyfelei valóban beírnak, a szolgáltatási területén belül. A keresőkifejezéseket és a területet kezdés előtt közösen meghatározzuk és írásban rögzítjük.'],
  ['Mit tartalmaz a 300.000 Ft-os induló munka?', 'Teljes versenytárselemzést, weboldal-optimalizálást, Google Cégprofil-optimalizálást, kétheti frissítéseket, helyezéskövetést és magas minőségű backlinkeket.'],
  ['Mit tartalmaz a 35.000 Ft-os havi fenntartás?', 'A megbeszélt Google Cégprofil-frissítéseket, helyezéskövetést, a szükséges optimalizálásokat és a folyamatos munkát a Top 3 helyezés eléréséig és megtartásáig.'],
  ['Mi történik, ha 90 nap alatt nem érjük el a megbeszélt Top 3 helyezést?', 'Ön nem fizet tovább, mi pedig díjmentesen folytatjuk a munkát addig, amíg el nem érjük. Nincs új számla, nincs kilépési díj, nincs vita róla.'],
  ['Milyen hozzáférést kell adnom?', 'Hozzáférést a Google Cégprofiljához, egy telefonszámot, amelyet valóban felvesznek, valamint képeket az elvégzett munkákról. Az első két hétben nagyjából egy órát kérünk az idejéből.'],
  ['Mennyi idő alatt készül el egy weboldal?', 'Egy egyszerűbb bemutatkozó weboldal általában 1–2 hét alatt elkészül. A pontos idő a tartalom és a funkciók mennyiségétől függ.'],
  ['Kötelező a havi weboldal-karbantartás?', 'Nem. A 15.000 Ft / hó weboldal-karbantartás opcionális, és nem azonos a Google Térkép Top 3 fenntartásával.'],
]

function Intro({ label, title }: { label: string; title: string }) {
  return <div className="flex max-w-3xl flex-col gap-4"><p className="eyebrow">{label}</p><h2 className="font-serif text-4xl leading-tight tracking-tight text-balance md:text-6xl">{title}</h2></div>
}

export function SiteContent() {
  const [open, setOpen] = useState(false)
  return <>
    <header className="sticky top-0 z-40 border-b border-border/70 bg-background/95 backdrop-blur"><div className="site-shell flex h-20 items-center justify-between gap-6"><a href="#top" className="flex items-center gap-3" aria-label="Kiszely Marketing kezdőlap"><Image src={logoUrl} alt="Kiszely Marketing logó" width={56} height={56} className="size-12 rounded-lg object-cover" priority /><span className="hidden font-bold tracking-tight sm:block">KISZELY MARKETING</span></a><nav className="hidden items-center gap-7 lg:flex" aria-label="Fő navigáció"><a className="nav-link" href="#top3">Top 3</a><a className="nav-link" href="#folyamat">90 napos terv</a><a className="nav-link" href="#weboldal">Weboldal</a><a className="nav-link" href="#arak">Árak</a><a className="nav-link" href="#kapcsolat">Kapcsolat</a></nav><div className="flex items-center gap-2"><a href="#kapcsolat" className="button-primary hidden sm:inline-flex">Ingyenes konzultáció <ArrowRight data-icon="inline-end" /></a><button className="button-ghost lg:hidden" onClick={() => setOpen(!open)} aria-expanded={open} aria-label={open ? 'Menü bezárása' : 'Menü megnyitása'}>{open ? <X /> : <Menu />}</button></div></div>{open && <nav className="site-shell flex flex-col gap-1 border-t border-border py-4 lg:hidden" aria-label="Mobil navigáció">{[['top3', 'Top 3'], ['folyamat', '90 napos terv'], ['weboldal', 'Weboldal'], ['arak', 'Árak'], ['kapcsolat', 'Kapcsolat']].map(([id, label]) => <a key={id} href={`#${id}`} onClick={() => setOpen(false)} className="rounded-md px-3 py-3 font-semibold hover:bg-muted">{label}</a>)}<a href="#kapcsolat" className="button-primary mt-2">Ingyenes konzultáció</a></nav>}</header>

    <main id="top">
      <section className="site-shell grid min-h-[calc(100svh-5rem)] items-center gap-12 py-16 lg:grid-cols-[1.05fr_.95fr] lg:py-24"><div className="flex flex-col items-start gap-7"><p className="eyebrow">Marketing kisvállalkozásoknak Magyarországon</p><h1 className="font-serif text-5xl leading-[.98] tracking-[-.045em] text-balance sm:text-6xl lg:text-8xl">Top 3 a Google Térképen 90 napon belül.</h1><p className="max-w-xl text-lg leading-relaxed text-muted-foreground"><strong>Vagy ingyen dolgozunk tovább.*</strong><br />A helyi keresések 85%-a a Google Térkép első 3 találatához kerül. Ha nincs az első 3-ban, gyakorlatilag láthatatlan.</p><p className="max-w-xl leading-relaxed text-muted-foreground">Helyi szolgáltató vállalkozásokat juttatunk be a Google Térkép első 3 találata közé. Nincs hosszú távú lekötés. Nincs 12 hónapnyi kifogás.</p><div className="flex flex-wrap gap-3"><a href="#kapcsolat" className="button-primary">Kérek ingyenes konzultációt <ArrowRight data-icon="inline-end" /></a><a href="#top3" className="button-outline">Ismerje meg a szolgáltatásokat</a></div></div><div className="relative overflow-hidden rounded-2xl border border-border bg-card p-3 shadow-xl"><Image src={mapGreenUrl} alt="Google Térkép Top 3 láthatóság szemléltetése" width={1632} height={964} className="h-auto w-full rounded-xl" priority /><div className="absolute bottom-7 left-7 rounded-xl bg-background/95 p-4 shadow-lg"><p className="text-xs font-bold uppercase tracking-wider text-primary">Cél</p><p className="font-serif text-2xl">Top 3 helyezés</p><p className="text-sm text-muted-foreground">90 napon belül</p></div></div></section>

      <section className="section muted-section"><div className="site-shell flex flex-col gap-5"><Intro label="A valódi probléma" title="Nem csörög a telefonja." /><div className="max-w-3xl text-xl leading-relaxed md:text-3xl"><p>Nem az árai miatt.</p><p>Nem az értékelései miatt.</p><p>Hanem azért, mert szinte senki nem jut túl a Google Térkép első 3 találatán.</p><p className="font-bold text-primary">És Ön nincs köztük.</p></div></div></section>

      <section id="top3" className="section bg-foreground text-background"><div className="site-shell grid items-center gap-12 lg:grid-cols-[.9fr_1.1fr]"><div className="flex flex-col gap-6"><p className="eyebrow text-accent">Google Térkép Top 3</p><h2 className="font-serif text-4xl leading-tight tracking-tight text-balance md:text-6xl">A szolgáltatás, ami a fő ajánlatunk.</h2><p className="leading-relaxed text-background/70">A célzott Google Cégprofil- és weboldal-optimalizálással a szolgáltatási területén a megfelelő emberek találjanak Önre, amikor az Ön szolgáltatását keresik.</p><ul className="flex flex-col gap-3">{['Teljes versenytárselemzés', 'Teljes weboldal-optimalizálás', 'Google Cégprofil optimalizálás', 'Kétheti frissítések', 'Helyezéskövetés a fő keresőkifejezésre', 'Magas minőségű backlinkek'].map(item => <li key={item} className="flex items-center gap-3"><Check className="size-5 text-accent" /><span>{item}</span></li>)}</ul><div className="border-t border-background/20 pt-5"><p className="text-sm text-background/60">Egyszeri díj</p><p className="font-serif text-4xl">300.000 Ft</p><p className="mt-2 text-sm text-background/60">Fenntartási díj: <strong className="text-background">35.000 Ft / hónap</strong></p></div><a href="#kapcsolat" className="button-light self-start">Kérek ingyenes konzultációt <ArrowRight data-icon="inline-end" /></a></div><div className="rounded-2xl bg-background p-3"><Image src={mapRedUrl} alt="Példa Google Térkép láthatóságra" width={1632} height={964} className="w-full rounded-xl" /></div></div></section>

      <section className="section"><div className="site-shell grid gap-8 lg:grid-cols-3"><div className="lg:col-span-1"><Intro label="A garancia" title="90 nap. Top 3." /><p className="mt-5 text-xl font-semibold text-primary">Vagy egy forinttal sem fizet többet.</p></div><div className="grid gap-8 md:grid-cols-3 lg:col-span-2"><article><h3 className="text-xl font-bold">Mit jelent pontosan a Top 3?</h3><p className="mt-3 leading-relaxed text-muted-foreground">Top 3 helyezés a Google Térkép találatai között azokra a keresésekre, amelyeket az ügyfelei valóban beírnak, a szolgáltatási területén belül. A pontos keresőkifejezéseket és a területet még a kezdés előtt, a konzultáción közösen meghatározzuk és írásban rögzítjük.</p></article><article><h3 className="text-xl font-bold">Mi történik a 91. napon?</h3><p className="mt-3 leading-relaxed text-muted-foreground">Ha addig nem érjük el a megbeszélt Top 3 helyezést, Ön nem fizet tovább, mi pedig díjmentesen folytatjuk a munkát addig, amíg el nem érjük. Nincs új számla, nincs kilépési díj, nincs vita róla.</p></article><article><h3 className="text-xl font-bold">Mire van szükségünk Öntől?</h3><p className="mt-3 leading-relaxed text-muted-foreground">Hozzáférés a Google Cégprofiljához, egy telefonszám, amelyet valóban felvesznek, valamint képek az elvégzett munkákról. Az első két hétben nagyjából egy órát kérünk az idejéből.</p></article></div></div></section>

      <section id="folyamat" className="section muted-section"><div className="site-shell flex flex-col gap-12"><div className="grid gap-5 lg:grid-cols-[1fr_.8fr]"><Intro label="A 90 napos terv" title="Kilencven nap, előre megtervezve." /><p className="self-end leading-relaxed text-muted-foreground">Nincs rejtély, és nincs olyan havi riport, tele grafikonokkal, amelyeket senki nem olvas el. Pontosan tudja, mi történik és mikor.</p></div><div className="grid gap-6 lg:grid-cols-3">{roadmap.map(([phase, range, items]) => <article key={phase} className="rounded-2xl border border-border bg-background p-6 lg:p-7"><div className="flex items-baseline justify-between gap-3 border-b border-border pb-5"><h3 className="font-serif text-3xl text-primary">{phase}</h3><span className="text-sm font-bold text-muted-foreground">{range}</span></div><div className="mt-5 flex flex-col gap-5">{items.map(([day, text]) => <div key={day}><p className="font-bold">{day}</p><p className="mt-1 text-sm leading-relaxed text-muted-foreground">{text}</p></div>)}</div></article>)}</div></div></section>

      <section className="section"><div className="site-shell grid items-center gap-12 lg:grid-cols-[.85fr_1.15fr]"><div><Intro label="Példa / illusztráció" title="Lássa pontosan, hol találják meg a Google Térképen" /><p className="mt-5 text-sm leading-relaxed text-muted-foreground">Szemléltető helyezések, nem valós ügyféleredmény és nem ígért javulás. A pontok különböző keresési helyeket, a számok a helyezést jelölik.</p></div><div className="grid gap-5 sm:grid-cols-2"><div><Image src={mapRedUrl} alt="Gyenge láthatóság szemléltetése" width={1632} height={964} className="rounded-xl border border-border" /><p className="mt-3 font-bold">Gyenge láthatóság</p></div><div><Image src={mapGreenUrl} alt="Javult láthatóság szemléltetése" width={1632} height={964} className="rounded-xl border border-border" /><p className="mt-3 font-bold">Javult láthatóság</p></div></div></div></section>

      <RoiCalculator language="hu" />

      <section id="weboldal" className="section"><div className="site-shell flex flex-col gap-12"><div className="grid gap-8 lg:grid-cols-[1fr_.7fr]"><Intro label="Weboldal készítés" title="Professzionális weboldal-készítés" /><p className="self-end leading-relaxed text-muted-foreground">Egy jól megtervezett weboldal nem dísz, hanem üzleti eszköz, amely bemutatja a szolgáltatásait és megkönnyíti a kapcsolatfelvételt.</p></div><div className="grid gap-px border-y border-border bg-border md:grid-cols-2 lg:grid-cols-3">{webFeatures.map(([title, text], i) => <article key={title} className="flex min-h-64 flex-col justify-between gap-8 bg-background p-7 lg:p-9"><span className="font-serif text-3xl text-primary">0{i + 1}</span><div><h3 className="text-xl font-bold">{title}</h3><p className="mt-2 leading-relaxed text-muted-foreground">{text}</p></div></article>)}</div></div></section>

      <section id="arak" className="section muted-section"><div className="site-shell flex flex-col gap-12"><div className="flex max-w-3xl flex-col gap-4"><p className="eyebrow">Árak</p><h2 className="font-serif text-4xl leading-tight tracking-tight md:text-6xl">Átlátható csomagok.</h2><p className="text-lg leading-relaxed text-muted-foreground">A Google Térkép Top 3 a fő ajánlatunk. A weboldal készítés külön szolgáltatás, a kettő díjai nem keverednek.</p></div><div className="grid gap-5 lg:grid-cols-3"><article className="price-card featured"><p className="eyebrow">Fő ajánlat</p><h3>Google Térkép Top 3</h3><strong>300.000 Ft</strong><p>Egyszeri induló díj a teljes optimalizálási munkára.</p><p className="text-sm font-bold text-primary">Fenntartás: 35.000 Ft / hónap</p><ul>{['Teljes versenytárselemzés', 'Teljes weboldal-optimalizálás', 'Google Cégprofil optimalizálás', 'Kétheti frissítések', 'Helyezéskövetés', 'Magas minőségű backlinkek'].map(x => <li key={x}><Check />{x}</li>)}</ul><a href="#kapcsolat" className="button-primary">Konzultációt kérek <ArrowRight data-icon="inline-end" /></a></article><article className="price-card"><p className="eyebrow">Weboldal</p><h3>Starter</h3><strong>90.000–160.000 Ft</strong><p>Professzionális, mobilbarát bemutatkozó weboldal.</p><ul>{['Egyedi dizájn', 'Mobilbarát kialakítás', 'Kapcsolatfelvételi űrlap', 'SEO alapok'].map(x => <li key={x}><Check />{x}</li>)}</ul><a href="#kapcsolat" className="button-outline">Ajánlatot kérek <ArrowRight data-icon="inline-end" /></a></article><article className="price-card"><p className="eyebrow">Weboldal</p><h3>Premium</h3><strong>170.000 Ft+</strong><p>Összetettebb igényekre, több oldallal és funkcióval.</p><ul>{['Több aloldal', 'Egyedi funkciók', 'Foglalási rendszerek', 'Fejlett SEO alapok'].map(x => <li key={x}><Check />{x}</li>)}</ul><a href="#kapcsolat" className="button-outline">Ajánlatot kérek <ArrowRight data-icon="inline-end" /></a></article></div><p className="text-sm leading-relaxed text-muted-foreground"><strong>Weboldal-karbantartás:</strong> 15.000 Ft / hó, opcionális. Ez nem azonos a Google Térkép Top 3 fenntartási díjával.</p></div></section>

      <section id="iparagak" className="section"><div className="site-shell flex flex-col gap-10"><Intro label="Iparágak" title="Szakterületek" /><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{industries.map(item => <div key={item} className="rounded-xl border border-border bg-card p-4"><p className="font-bold">{item}</p><p className="mt-1 text-sm text-muted-foreground">Marketing {item.toLowerCase()}nek</p></div>)}</div></div></section>

      <section className="section"><div className="site-shell grid items-center gap-12 lg:grid-cols-[.8fr_1.2fr]"><div className="overflow-hidden rounded-2xl"><Image src={founderUrl} alt="Tamás, a Kiszely Marketing alapítója" width={1120} height={1400} className="w-full object-cover" /></div><div className="flex flex-col gap-5"><p className="eyebrow">Tamás</p><h2 className="font-serif text-4xl leading-tight md:text-6xl">Személyes figyelem. Átlátható munka.</h2><p className="text-lg leading-relaxed text-muted-foreground">Tamás, a Kiszely Marketing alapítója.</p><a href="#kapcsolat" className="button-primary self-start">Beszéljük át <ArrowRight data-icon="inline-end" /></a></div></div></section>

      <section className="section muted-section"><div className="site-shell flex max-w-4xl flex-col gap-8"><Intro label="Gyakori kérdések" title="Amit érdemes tudni az indulás előtt." />{faqs.map(([q, a]) => <details key={q} className="group border-t border-border py-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-5 text-lg font-bold">{q}<ChevronDown className="size-5 shrink-0 transition-transform group-open:rotate-180" /></summary><p className="max-w-3xl pt-4 leading-relaxed text-muted-foreground">{a}</p></details>)}</div></section>

      <section id="kapcsolat" className="section"><div className="site-shell grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div className="flex flex-col gap-5"><p className="eyebrow">Kapcsolat</p><h2 className="font-serif text-4xl leading-tight md:text-6xl">Beszéljük át, mire van szüksége az online jelenlétben.</h2><p className="text-lg leading-relaxed text-muted-foreground">Írja meg röviden, mivel foglalkozik és milyen weboldalt vagy online megoldást szeretne. Tamás személyesen válaszol a megkeresésére.</p><div className="border-t border-border pt-5 text-sm"><p className="font-bold">E-mail</p><a href="mailto:tokolitamas7@gmail.com" className="text-primary hover:underline">tokolitamas7@gmail.com</a></div></div><ContactForm language="hu" /></div></section>
    </main>

    <footer className="border-t border-border py-10"><div className="site-shell flex flex-col gap-5 text-sm text-muted-foreground"><div className="flex flex-col gap-1 sm:flex-row sm:items-center sm:justify-between"><p className="font-bold text-foreground">Kiszely Marketing</p><p>Marketing kisvállalkozásoknak Magyarországon</p><p>© 2026 Kiszely Marketing. Minden jog fenntartva.</p></div><nav className="flex flex-wrap gap-x-5 gap-y-2" aria-label="Lábléc navigáció"><a href="#top3" className="hover:text-foreground">Google Térkép Top 3</a><a href="#top3" className="hover:text-foreground">Google Cégprofil optimalizálás</a><a href="#weboldal" className="hover:text-foreground">Weboldal készítés</a><a href="#iparagak" className="hover:text-foreground">Iparágak</a><a href="#arak" className="hover:text-foreground">Árak</a><a href="#kapcsolat" className="hover:text-foreground">Kapcsolat</a></nav></div></footer>
  </>
}
